export const selectStyles = (hasError) => ({
  control: (base, state) => ({
    ...base,
    borderRadius: "0.75rem",
    borderColor: hasError ? "#ef4444" : state.isFocused ? "#F5C518" : "#e5e7eb",
    boxShadow: hasError ? "0 0 0 3px rgba(239,68,68,0.1)" : "none",
    backgroundColor: hasError ? "#fff5f5" : "#ffffff",
    minHeight: "42px",
    fontSize: "0.875rem",
    cursor: "pointer",
    "&:hover": { borderColor: hasError ? "#ef4444" : "#F5C518" },
  }),
  placeholder: (base) => ({ ...base, color: "#9ca3af", fontSize: "0.875rem" }),
  singleValue: (base) => ({ ...base, color: "#111111", fontSize: "0.875rem" }),
  indicatorSeparator: () => ({ display: "none" }),
  dropdownIndicator: (base, state) => ({
    ...base,
    color: state.isFocused ? "#F5C518" : "#9ca3af",
    transition: "transform 0.2s",
    transform: state.selectProps.menuIsOpen ? "rotate(180deg)" : "rotate(0deg)",
  }),
  menu: (base) => ({
    ...base,
    borderRadius: "0.75rem",
    overflow: "hidden",
    zIndex: 99,
    boxShadow: "0 4px 20px rgba(0,0,0,0.08)",
    border: "1px solid #e5e7eb",
  }),
  menuList: (base) => ({ ...base, padding: "4px" }),
  option: (base, state) => ({
    ...base,
    fontSize: "0.875rem",
    borderRadius: "0.5rem",
    backgroundColor: state.isSelected ? "#FEF3C7" : state.isFocused ? "#FFFBEB" : "transparent",
    color: "#111111",
    fontWeight: state.isSelected ? "600" : "400",
    cursor: "pointer",
    margin: "1px 0",
  }),
});